/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Ui;

import car.Catalog;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author riteesh
 */
public class ViewJPanel extends javax.swing.JPanel {

    Catalog catalog;
    
    
    public ViewJPanel(Catalog catalog) {
        initComponents();
        this.catalog = catalog;
        displayCatalog();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        txtVServiceRecords = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtVWarrantyYear = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtVSeatingCapacity = new javax.swing.JTextField();
        txtVEngineNumber = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtVYear = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtVColor = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtVModel = new javax.swing.JTextField();
        txtVCompany = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtVOwnerName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtVLicensePlate = new javax.swing.JTextField();
        txtVTelephone = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtVEmail = new javax.swing.JTextField();
        txtVLicense = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtVSSN = new javax.swing.JTextField();
        txtVAddress = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        txtWarrantyYear1 = new javax.swing.JTextField();

        txtVServiceRecords.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVServiceRecords.setMinimumSize(new java.awt.Dimension(100, 100));
        txtVServiceRecords.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVServiceRecordsActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel12.setText("E-mail:");

        txtVWarrantyYear.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVWarrantyYear.setMinimumSize(new java.awt.Dimension(100, 100));
        txtVWarrantyYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVWarrantyYearActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("License:");

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel14.setText("SSN:");

        txtVSeatingCapacity.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVSeatingCapacity.setMinimumSize(new java.awt.Dimension(100, 26));

        txtVEngineNumber.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVEngineNumber.setMinimumSize(new java.awt.Dimension(100, 26));

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel15.setText("Address:");

        txtVYear.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVYear.setMinimumSize(new java.awt.Dimension(100, 26));

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel16.setText("Servicerecords:");

        txtVColor.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVColor.setMinimumSize(new java.awt.Dimension(100, 26));

        jLabel17.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel17.setText("WarrantyYear:");

        txtVModel.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVModel.setMinimumSize(new java.awt.Dimension(100, 26));

        txtVCompany.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVCompany.setMinimumSize(new java.awt.Dimension(100, 26));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Color:");

        txtVOwnerName.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVOwnerName.setMinimumSize(new java.awt.Dimension(100, 100));
        txtVOwnerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVOwnerNameActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel5.setText("Year:");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel1.setText("View Profile");
        jLabel1.setAlignmentY(0.0F);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("EngineNumber:");

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("SeatingCapacity:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("Company:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Model:");

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel8.setText("LicensePlate:");

        txtVLicensePlate.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVLicensePlate.setMinimumSize(new java.awt.Dimension(100, 26));

        txtVTelephone.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVTelephone.setMinimumSize(new java.awt.Dimension(100, 100));
        txtVTelephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVTelephoneActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel9.setText("OwnerName:");

        txtVEmail.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVEmail.setMinimumSize(new java.awt.Dimension(100, 100));
        txtVEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVEmailActionPerformed(evt);
            }
        });

        txtVLicense.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVLicense.setMinimumSize(new java.awt.Dimension(100, 100));
        txtVLicense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVLicenseActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel10.setText("Telephone:");

        txtVSSN.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVSSN.setMinimumSize(new java.awt.Dimension(100, 100));
        txtVSSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVSSNActionPerformed(evt);
            }
        });

        txtVAddress.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtVAddress.setMinimumSize(new java.awt.Dimension(100, 100));
        txtVAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVAddressActionPerformed(evt);
            }
        });

        lblPhoto.setText("Photo:");

        txtWarrantyYear1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        txtWarrantyYear1.setMinimumSize(new java.awt.Dimension(100, 100));
        txtWarrantyYear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWarrantyYear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel11)
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel10)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel17)
                            .addComponent(jLabel3)
                            .addComponent(lblPhoto))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtVSeatingCapacity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtVOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtVLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtVTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVServiceRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtVWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVEngineNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVYear, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVColor, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVModel, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtVCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(jLabel1)))
                .addContainerGap(116, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtWarrantyYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(401, 401, 401)
                        .addComponent(jLabel11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtVCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtVModel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtVColor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtVYear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtVEngineNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtVSeatingCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txtVLicensePlate, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(txtVOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtVTelephone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtVEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(txtVLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtVSSN, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtVAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(txtVServiceRecords, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(txtVWarrantyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtWarrantyYear1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhoto))
                .addContainerGap(64, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtVServiceRecordsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVServiceRecordsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVServiceRecordsActionPerformed

    private void txtVWarrantyYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVWarrantyYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVWarrantyYearActionPerformed

    private void txtVOwnerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVOwnerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVOwnerNameActionPerformed

    private void txtVTelephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVTelephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVTelephoneActionPerformed

    private void txtVEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVEmailActionPerformed

    private void txtVLicenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVLicenseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVLicenseActionPerformed

    private void txtVSSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVSSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVSSNActionPerformed

    private void txtVAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVAddressActionPerformed

    private void txtWarrantyYear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWarrantyYear1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWarrantyYear1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JTextField txtVAddress;
    private javax.swing.JTextField txtVColor;
    private javax.swing.JTextField txtVCompany;
    private javax.swing.JTextField txtVEmail;
    private javax.swing.JTextField txtVEngineNumber;
    private javax.swing.JTextField txtVLicense;
    private javax.swing.JTextField txtVLicensePlate;
    private javax.swing.JTextField txtVModel;
    private javax.swing.JTextField txtVOwnerName;
    private javax.swing.JTextField txtVSSN;
    private javax.swing.JTextField txtVSeatingCapacity;
    private javax.swing.JTextField txtVServiceRecords;
    private javax.swing.JTextField txtVTelephone;
    private javax.swing.JTextField txtVWarrantyYear;
    private javax.swing.JTextField txtVYear;
    private javax.swing.JTextField txtWarrantyYear1;
    // End of variables declaration//GEN-END:variables

    private void displayCatalog() {
        
        txtVCompany.setText(catalog.getCompany());
        txtVModel.setText(catalog.getModel());
        txtVColor.setText(catalog.getColor());
        txtVYear.setText(catalog.getYear());
        txtVEngineNumber.setText(catalog.getEngineNumber());
        txtVSeatingCapacity.setText(catalog.getSeatingCapacity());
        txtVLicensePlate.setText(catalog.getLicensePlate());
        txtVOwnerName.setText(catalog.getOwnerName());
        txtVTelephone.setText(catalog.getOwnerTelephone());
        txtVEmail.setText(catalog.getOwnerEmail());
        txtVLicense.setText(catalog.getOwnerLicense());
        txtVSSN.setText(catalog.getOwnerSSN());
        txtVAddress.setText(catalog.getOwnerAddress());
        txtVServiceRecords.setText(catalog.getServiceRecords());
        txtVWarrantyYear.setText(catalog.getWarrantyYear());
        
        String filename1 = catalog.getPhoto();
        lblPhoto.setText(filename1);
        ImageIcon imageIcon1 = new ImageIcon(new ImageIcon(filename1).getImage().getScaledInstance(138, 152, Image.SCALE_DEFAULT));
        lblPhoto.setIcon(imageIcon1);
    
    }
}
